# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/notebooks',
                'doc_host': 'https://rrampage.github.io',
                'git_url': 'https://github.com/rrampage/notebooks/tree/master',
                'lib_path': 'notebooks'},
  'syms': {'notebooks.core': {}, 'notebooks.crypto_1': {}}}
